<?php


namespace smn\dbars\Catalog;


class ColumnCatalogObject extends CatalogObject implements ColumnCatalogObjectInterface
{

    public function __construct(string $name)
    {
        parent::__construct($name, self::CHILD_COLUMN);
        $this->phs->setPattern('{column_name}');
        $this->phs->addPlaceHolder('column_name', function (ColumnCatalogObjectInterface $instance) {
            return $instance->getName();
        }, [$this]);
    }

    public function setTable(string $table_name)
    {
        $this->setParent($table_name, self::CHILD_TABLE);
    }

    public function setTableInstance(TableCatalogObjectInterface $table)
    {
        $this->setParentInstance($table);
    }

    public function getTable(): ?TableCatalogObjectInterface
    {
        return $this->getParent();
    }
    public function toString(): string
    {
        if ($this->getTable() != null) {
            $this->phs->setPattern('{parent}.{column_name}');
            $this->phs->addPlaceHolder('parent', function (ColumnCatalogObjectInterface $instance) {
                return $instance->getTable()->toString();
            }, [$this]);
        }

        return parent::toString(); // TODO: Change the autogenerated stub
    }
}